<link rel="manifest" href="/manifest.webmanifest">
<meta name="theme-color" content="#355872">
<meta name="application-name" content="Harviana">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Harviana">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="msapplication-TileColor" content="#355872">
<meta name="msapplication-tap-highlight" content="no">
<meta name="format-detection" content="telephone=no">
