<x-admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-lg lg:text-xl text-gray-800 leading-tight">
            {{ __('Reports & Analytics') }}
        </h2>
        <p class="text-xs lg:text-sm text-gray-600 mt-1">Generate comprehensive agricultural reports and insights</p>
    </x-slot>

    <div class="py-4 lg:py-8 px-4 sm:px-6 lg:px-8">
        <div class="max-w-7xl mx-auto">
            
            <!-- Statistics Overview -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 lg:gap-4 mb-4 lg:mb-6">
                <!-- Total Records -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-blue-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Crop Data Records</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ number_format($stats['totalRecords']) }}</p>
                            <p class="text-xs text-gray-500 mt-1">{{ $stats['dateRange']['start'] }} - {{ $stats['dateRange']['end'] }}</p>
                        </div>
                        <div class="bg-blue-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <!-- Predictions -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-purple-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Total Predictions</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ number_format($stats['totalPredictions']) }}</p>
                            <p class="text-xs text-gray-500 mt-1">Generated by users</p>
                        </div>
                        <div class="bg-purple-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <!-- Coverage -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-green-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Data Coverage</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ $stats['municipalities'] }}</p>
                            <p class="text-xs text-gray-500 mt-1">Municipalities, {{ $stats['crops'] }} crop types</p>
                        </div>
                        <div class="bg-green-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"></path>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Report Types Grid -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6 mb-4 lg:mb-6">
                
                <!-- Production Summary Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-blue-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Production Summary</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Comprehensive overview of crop production by municipality and crop type. Includes total production, area harvested, and productivity metrics.</p>
                                <a href="{{ route('admin.reports.production-summary') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Prediction Analytics Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-purple-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Prediction Analytics</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Detailed analysis of prediction accuracy, success rates, and user activity. Track model performance and confidence scores over time.</p>
                                <a href="{{ route('admin.reports.prediction-analytics') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-purple-600 text-white text-sm rounded-lg hover:bg-purple-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Comparative Analysis Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-green-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Comparative Analysis</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Compare production metrics across municipalities, crops, or time periods. Identify trends and patterns in agricultural data.</p>
                                <a href="{{ route('admin.reports.comparative-analysis') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-green-600 text-white text-sm rounded-lg hover:bg-green-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- User Activity Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-orange-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">User Activity</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Track farmer engagement and prediction usage. Monitor active users and system adoption rates across regions.</p>
                                <a href="{{ route('admin.reports.user-activity') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-orange-600 text-white text-sm rounded-lg hover:bg-orange-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Recent Activity -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-4 lg:p-6">
                    <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-4">Recent Predictions Activity</h3>
                    
                    @if($recentPredictions->count() > 0)
                        <div class="space-y-3">
                            @foreach($recentPredictions as $prediction)
                                <div class="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
                                    <div class="flex-shrink-0 h-10 w-10 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center text-white font-semibold">
                                        {{ strtoupper(substr($prediction->user->name ?? 'U', 0, 1)) }}
                                    </div>
                                    <div class="flex-1 min-w-0">
                                        <p class="text-sm font-medium text-gray-900">{{ $prediction->user->name ?? 'Unknown' }}</p>
                                        <p class="text-xs text-gray-600">
                                            Predicted {{ number_format($prediction->predicted_production_mt, 2) }} MT of {{ $prediction->crop }} 
                                            in {{ $prediction->municipality }}
                                        </p>
                                    </div>
                                    <div class="text-right flex-shrink-0">
                                        <p class="text-xs text-gray-500">{{ $prediction->created_at->diffForHumans() }}</p>
                                        <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">
                                            {{ number_format(($prediction->confidence_score ?? 0) * 100, 1) }}% confidence
                                        </span>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @else
                        <div class="text-center py-8 text-gray-500">
                            <svg class="mx-auto h-12 w-12 text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                            </svg>
                            <p>No recent predictions</p>
                        </div>
                    @endif
                </div>
            </div>

        </div>
    </div>
</x-admin-layout>
