<x-admin-layout>
    <div class="py-4 lg:py-8 px-4 sm:px-6 lg:px-8">
        <div class="max-w-7xl mx-auto">
            
            <!-- Statistics Overview -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 lg:gap-4 mb-4 lg:mb-6">
                <!-- Total Records -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-blue-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Crop Data Records</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ number_format($stats['totalRecords']) }}</p>
                            <p class="text-xs text-gray-500 mt-1">{{ $stats['dateRange']['start'] }} - {{ $stats['dateRange']['end'] }}</p>
                        </div>
                        <div class="bg-blue-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <!-- Predictions -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-purple-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Total Predictions</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ number_format($stats['totalPredictions']) }}</p>
                            <p class="text-xs text-gray-500 mt-1">Generated by users</p>
                        </div>
                        <div class="bg-purple-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                            </svg>
                        </div>
                    </div>
                </div>

                <!-- Coverage -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-4 lg:p-6 border-l-4 border-green-500">
                    <div class="flex items-center justify-between">
                        <div class="min-w-0">
                            <p class="text-xs lg:text-sm text-gray-600 mb-1">Data Coverage</p>
                            <p class="text-2xl lg:text-3xl font-bold text-gray-900">{{ $stats['municipalities'] }}</p>
                            <p class="text-xs text-gray-500 mt-1">Municipalities, {{ $stats['crops'] }} crop types</p>
                        </div>
                        <div class="bg-green-100 p-3 rounded-full flex-shrink-0">
                            <svg class="w-6 h-6 lg:w-8 lg:h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"></path>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Report Types Grid -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6 mb-4 lg:mb-6">
                
                <!-- Production Summary Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-blue-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Production Summary</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Comprehensive overview of crop production by municipality and crop type. Includes total production, area harvested, and productivity metrics.</p>
                                <a href="{{ route('admin.reports.production-summary') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Prediction Analytics Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-purple-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Prediction Analytics</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Detailed analysis of prediction accuracy, success rates, and user activity. Track model performance and confidence scores over time.</p>
                                <a href="{{ route('admin.reports.prediction-analytics') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-purple-600 text-white text-sm rounded-lg hover:bg-purple-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Comparative Analysis Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-green-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">Comparative Analysis</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Compare production metrics across municipalities, crops, or time periods. Identify trends and patterns in agricultural data.</p>
                                <a href="{{ route('admin.reports.comparative-analysis') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-green-600 text-white text-sm rounded-lg hover:bg-green-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- User Activity Report -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition">
                    <div class="p-4 lg:p-6">
                        <div class="flex items-start gap-4">
                            <div class="bg-orange-100 p-3 rounded-lg flex-shrink-0">
                                <svg class="w-6 h-6 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <h3 class="text-base lg:text-lg font-semibold text-gray-900 mb-2">User Activity</h3>
                                <p class="text-xs lg:text-sm text-gray-600 mb-4">Track farmer engagement and prediction usage. Monitor active users and system adoption rates across regions.</p>
                                <a href="{{ route('admin.reports.user-activity') }}" 
                                   class="inline-flex items-center px-4 py-2 bg-orange-600 text-white text-sm rounded-lg hover:bg-orange-700 transition">
                                    Generate Report
                                    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Prediction Snapshot -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-4 lg:p-6">
                    <div class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-2 mb-4">
                        <div>
                            <h3 class="text-base lg:text-lg font-semibold text-gray-900">Prediction Snapshot</h3>
                            <p class="text-xs lg:text-sm text-gray-600 mt-1">
                                Quick report signals from recent successful predictions
                            </p>
                        </div>
                        <p class="text-xs text-gray-500">
                            30-day window since {{ $predictionSummary['window_start']->format('M d, Y') }}
                        </p>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-3 gap-3 lg:gap-4">
                        <div class="rounded-2xl border border-blue-100 bg-blue-50 p-4">
                            <div class="flex items-start justify-between gap-3">
                                <div>
                                    <p class="text-xs font-semibold uppercase tracking-wide text-blue-700">This Week</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">
                                        {{ number_format($predictionSummary['predictions_this_week']) }}
                                    </p>
                                    <p class="mt-1 text-xs text-gray-600">
                                        Successful predictions since {{ $predictionSummary['week_start']->format('M d') }}
                                    </p>
                                </div>
                                <div class="rounded-xl bg-white/80 p-2 text-blue-600">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3v18h18M7 14l3-3 4 4 5-7"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        <div class="rounded-2xl border border-emerald-100 bg-emerald-50 p-4">
                            <div class="flex items-start justify-between gap-3">
                                <div>
                                    <p class="text-xs font-semibold uppercase tracking-wide text-emerald-700">Avg Confidence</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">
                                        {{ number_format($predictionSummary['average_confidence'] * 100, 1) }}%
                                    </p>
                                    <p class="mt-1 text-xs text-gray-600">
                                        Mean confidence score over the last 30 days
                                    </p>
                                </div>
                                <div class="rounded-xl bg-white/80 p-2 text-emerald-600">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5-2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        <div class="rounded-2xl border border-amber-100 bg-amber-50 p-4">
                            <div class="flex items-start justify-between gap-3">
                                <div>
                                    <p class="text-xs font-semibold uppercase tracking-wide text-amber-700">Busiest Municipality</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">
                                        {{ $predictionSummary['top_municipality']->municipality ?? 'No data yet' }}
                                    </p>
                                    <p class="mt-1 text-xs text-gray-600">
                                        @if($predictionSummary['top_municipality'])
                                            {{ number_format($predictionSummary['top_municipality']->total) }} successful predictions in the last 30 days
                                        @else
                                            No successful predictions recorded in the current 30-day window
                                        @endif
                                    </p>
                                </div>
                                <div class="rounded-xl bg-white/80 p-2 text-amber-600">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a2 2 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path>
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</x-admin-layout>
